Update sonarqube.yml

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -25,8 +25,25 @@ jobs:
 
       - name: Install SonarScanner 10.6
         run: |
-          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-10.6.0.31212-linux.zip
+          # Download SonarScanner 10.6
+          curl -L -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-10.6.0.31212-linux.zip
+          
+          # Check if the file was downloaded correctly
+          if [ ! -f sonar-scanner.zip ]; then
+            echo "Failed to download SonarScanner. Exiting."
+            exit 1
+          fi
+
+          # Unzip the downloaded file
           unzip sonar-scanner.zip
+          
+          # Check if unzip was successful
+          if [ ! -d "sonar-scanner-10.6.0.31212-linux" ]; then
+            echo "Failed to unzip SonarScanner. Exiting."
+            exit 1
+          fi
+
+          # Move and create a symbolic link
           sudo mv sonar-scanner-10.6.0.31212-linux /opt/sonar-scanner
           sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
 
@@ -37,3 +54,4 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: 'https://sonarcloud.io/'
+
